/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.herokuapp.studentms;

import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kim Nguyen
 */
public class StudentMS extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel dtablemodel = new DefaultTableModel();
    /**
     * Creates new form StudentMS (Student Data Management System)
     */
    public StudentMS() {
        initComponents();
        
        Object col[] = {"Student_ID", "CourseCode","Math", "English", "Biology","InfoTech",
            "Chemistry","Physic","AddMath","Business", "TotalScore", "Average","Ranking"};
        dtablemodel.setColumnIdentifiers(col);
        jTableStudentRecord.setModel(dtablemodel);
        connection = StudentMS.ConnectDb();
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxCourseCode = new javax.swing.JComboBox<>();
        jtxtMath = new javax.swing.JTextField();
        jLabelBusiness = new javax.swing.JLabel();
        jtxtEnglish = new javax.swing.JTextField();
        jtxtBiology = new javax.swing.JTextField();
        jtxtInfoTech = new javax.swing.JTextField();
        jtxtChemistry = new javax.swing.JTextField();
        jtxtPhysic = new javax.swing.JTextField();
        jtxtAddMath = new javax.swing.JTextField();
        jtxtBusiness = new javax.swing.JTextField();
        jLabelStudentID = new javax.swing.JLabel();
        jtxtStudentID = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jLabelRanking = new javax.swing.JLabel();
        jtxtTotalScore = new javax.swing.JTextField();
        jtxtAverage = new javax.swing.JTextField();
        jtxtRanking = new javax.swing.JTextField();
        jLabelCourseCode = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelMath = new javax.swing.JLabel();
        jLabelEnglish = new javax.swing.JLabel();
        jLabelBiology = new javax.swing.JLabel();
        jLabelInfoTech = new javax.swing.JLabel();
        jLabelChemistry = new javax.swing.JLabel();
        jLabelPhysic = new javax.swing.JLabel();
        jLabelAddMath = new javax.swing.JLabel();
        jLabelTotalScore = new javax.swing.JLabel();
        jLabelAverage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTranscript = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudentRecord = new javax.swing.JTable();
        jbtnResult = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 224, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 12), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxCourseCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ART123", "BUS456", "COM789", "TEC098", "ENG123", "PHI456", "PSY789", "MAN098" }));
        jPanel1.add(jComboBoxCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, 40));

        jtxtMath.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMathKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 150, 40));

        jLabelBusiness.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelBusiness.setText("Business:");
        jPanel1.add(jLabelBusiness, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jtxtEnglish.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEnglishKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 150, 40));

        jtxtBiology.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtBiology.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBiologyKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtBiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 150, 40));

        jtxtInfoTech.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtInfoTech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtInfoTechKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtInfoTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 150, 40));

        jtxtChemistry.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtChemistry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChemistryKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 150, 40));

        jtxtPhysic.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtPhysic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPhysicKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtPhysic, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 150, 40));

        jtxtAddMath.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtAddMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAddMathKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtAddMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 150, 40));

        jtxtBusiness.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtBusiness.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBusinessKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtBusiness, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 150, 40));

        jLabelStudentID.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelStudentID.setText("Student_ID:");
        jPanel1.add(jLabelStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jtxtStudentID.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jtxtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentIDActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, 40));

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelLastName.setText("Last Name:");
        jPanel1.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jtxtLastName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jtxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 150, 40));

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelFirstName.setText("First Name:");
        jPanel1.add(jLabelFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jtxtFirstName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 40));

        jLabelRanking.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelRanking.setText("Ranking:");
        jPanel1.add(jLabelRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jtxtTotalScore.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jtxtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, 40));

        jtxtAverage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jtxtAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, 40));

        jtxtRanking.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jtxtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 150, 40));

        jLabelCourseCode.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelCourseCode.setText("Course Code:");
        jPanel1.add(jLabelCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 310, -1));

        jLabelMath.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelMath.setText("Mathematic:");
        jPanel1.add(jLabelMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabelEnglish.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelEnglish.setText("English:");
        jPanel1.add(jLabelEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabelBiology.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelBiology.setText("Biology:");
        jPanel1.add(jLabelBiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabelInfoTech.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelInfoTech.setText("Info Tech:");
        jPanel1.add(jLabelInfoTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabelChemistry.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelChemistry.setText("Chemistry:");
        jPanel1.add(jLabelChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabelPhysic.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelPhysic.setText("Physic:");
        jPanel1.add(jLabelPhysic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabelAddMath.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelAddMath.setText("Add Math:");
        jPanel1.add(jLabelAddMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jLabelTotalScore.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelTotalScore.setText("Total Score:");
        jPanel1.add(jLabelTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabelAverage.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelAverage.setText("Average:");
        jPanel1.add(jLabelAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 12), "Transcript", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaTranscript.setColumns(20);
        jTextAreaTranscript.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jTextAreaTranscript.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTranscript);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 470, 490));

        jTableStudentRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_ID", "Course_Code", "Mathematic", "English", "Biology", "Computer", "Chemistry", "Physic", "Add Math", "Business", "Total_Score", "Average", "Ranking"
            }
        ));
        jScrollPane1.setViewportView(jTableStudentRecord);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1160, 200));

        jbtnResult.setBackground(new java.awt.Color(95, 158, 160));
        jbtnResult.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbtnResult.setText("Result");
        jbtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 170, 40));

        jbtnExit.setBackground(new java.awt.Color(95, 158, 160));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 700, 210, 40));

        jbtnReset.setBackground(new java.awt.Color(95, 158, 160));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, 170, 40));

        jbtnDelete.setBackground(new java.awt.Color(95, 158, 160));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, 170, 40));

        jbtnTranscript.setBackground(new java.awt.Color(95, 158, 160));
        jbtnTranscript.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbtnTranscript.setText("Transcript");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, 170, 40));

        jbtnPrint.setBackground(new java.awt.Color(95, 158, 160));
        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 700, 170, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.getContentPane().setBackground(new java.awt.Color(176, 224, 230));
    }//GEN-LAST:event_formWindowActivated

    //-------------------------------BUTTON-------------------------------------//
    private void jbtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultActionPerformed
        
        int[] Result = new int[14];
        Result[0] = Integer.parseInt(jtxtMath.getText());
        Result[1] = Integer.parseInt(jtxtEnglish.getText());
        Result[2] = Integer.parseInt(jtxtBiology.getText());
        Result[3] = Integer.parseInt(jtxtInfoTech.getText());
        Result[4] = Integer.parseInt(jtxtChemistry.getText());
        Result[5] = Integer.parseInt(jtxtPhysic.getText());
        Result[6] = Integer.parseInt(jtxtAddMath.getText());
        Result[7] = Integer.parseInt(jtxtBusiness.getText());
        
        // TotalScore
        Result[8] = (Result[0]+Result[1]+Result[2]+Result[3]+Result[4]+Result[5]+Result[6]+Result[7]);
        // Average
        Result[9] = (Result[0]+Result[1]+Result[2]+Result[3]+Result[4]+Result[5]+Result[6]+Result[7]) / 8;
        
        // Store result to jtxtTotalScore text field
        String TotalScore = String.format("%d", Result[8]);
        jtxtTotalScore.setText(TotalScore);
        
        // Store result to jtxtAverage text field
        String Average = String.format("%d", Result[9]);
        jtxtAverage.setText(Average);
        
        // --------------------Ranking if/else Statement--------------------------//
        if (Result[9] >= 90 && Result[9] <= 100) {
             jtxtRanking.setText("1st");
        } else if (Result[9] >= 70 && Result[9] <= 89) {
                    jtxtRanking.setText("2nd");
        } else if (Result[9] >= 60 && Result[9] <= 69) {
                    jtxtRanking.setText("3rd");
        } else if (Result[9] >= 0 && Result[9] <= 59) {
                    jtxtRanking.setText("FAIL");
        }
        //----------------------------------------DATABASE------------------------------------------------------//
        String sql = "INSERT INTO \"StudentData\" (\"Student_ID\", \"CourseCode\", \"Math\", \"English\", "
                + "\"Biology\", \"InfoTech\", \"Chemistry\", \"Physic\", \"AddMath\", \"Business\", \"TotalScore\", "
                + "\"Average\", \"Ranking\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try {
            //PreparedStatement
            pst = connection.prepareStatement(sql);
            pst.setString(1, jtxtStudentID.getText());
            pst.setString(2, (String) jComboBoxCourseCode.getSelectedItem());
            pst.setInt(3, Integer.parseInt(jtxtMath.getText()));
            pst.setInt(4, Integer.parseInt(jtxtEnglish.getText()));
            pst.setInt(5, Integer.parseInt(jtxtBiology.getText()));
            pst.setInt(6, Integer.parseInt(jtxtInfoTech.getText()));
            pst.setInt(7, Integer.parseInt(jtxtChemistry.getText()));
            pst.setInt(8, Integer.parseInt(jtxtPhysic.getText()));
            pst.setInt(9, Integer.parseInt(jtxtAddMath.getText()));
            pst.setInt(10, Integer.parseInt(jtxtBusiness.getText()));
            pst.setInt(11, Integer.parseInt(jtxtTotalScore.getText()));
            pst.setInt(12, Integer.parseInt(jtxtAverage.getText()));
            pst.setString(13, jtxtRanking.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "System Update Completed");
            //rs = ResultSet
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTable();
    }//GEN-LAST:event_jbtnResultActionPerformed

    private void jtxtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentIDActionPerformed

//---------------------------------SUBJECT FIELDS-----------------------------------//
    private void jtxtMathKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMathKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtMathKeyTyped

    private void jtxtEnglishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEnglishKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtEnglishKeyTyped

    private void jtxtBiologyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBiologyKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtBiologyKeyTyped

    private void jtxtInfoTechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtInfoTechKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtInfoTechKeyTyped

    private void jtxtChemistryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChemistryKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtChemistryKeyTyped

    private void jtxtPhysicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhysicKeyTyped
        /// field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtPhysicKeyTyped

    private void jtxtAddMathKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAddMathKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtAddMathKeyTyped

    private void jtxtBusinessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusinessKeyTyped
        // field will only accept numbers for score
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
            ||  (iNumber == KeyEvent.VK_BACKSPACE)
                    || (iNumber == KeyEvent.VK_DELETE)) {
        evt.consume();
        }
    }//GEN-LAST:event_jtxtBusinessKeyTyped

//---------------------------------------BUTTONS------------------------------------//
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit StudentDataMS?", "Student Data Management System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField temp=null;
        for (Component c:jPanel1.getComponents()) {
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                temp=(JTextField) c;
                temp.setText(null);
            }
        }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        jTextAreaTranscript.append("Student Result Recording System\n"
                + "Full Name: " + jtxtFirstName.getText() + " " +  jtxtLastName.getText() + "\t ID: " + jtxtStudentID.getText()
                + "\n===============================\n"
                + "Mathematic:\t\t" + jtxtMath.getText() + "\n"
                + "English:\t\t" + jtxtEnglish.getText() + "\n"
                + "Biology:\t\t" + jtxtBiology.getText() + "\n"
                + "InfoTech:\t\t" + jtxtInfoTech.getText() + "\n"
                + "Chemistry:\t\t" + jtxtChemistry.getText() + "\n"
                + "Physic:\t\t" + jtxtPhysic.getText() + "\n"
                + "AddMath:\t\t" + jtxtAddMath.getText() + "\n"
                + "Business:\t\t" + jtxtBusiness.getText() + "\n"
                + "===============================\n"
                + "Total Score:\t\t" + jtxtTotalScore.getText() + "\n"
                + "Average:\t\t" + jtxtAverage.getText() + "\n"
                + "Ranking:\t\t" + jtxtRanking.getText() + "\n"
        );
    }//GEN-LAST:event_jbtnTranscriptActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
                        try {
/**
                        PrinterJob job = PrinterJob.getPrinterJob();
                        String strDate = MessageFormat.format("{0,date,short} {0,time,short}", new Date());

                        MessageFormat[] header = new MessageFormat[3];
                        header[0] = new MessageFormat("Unofficial Transcript");
                        header[1] = new MessageFormat("");
                        header[2] = new MessageFormat("Printed: " + strDate);
                        
                        MessageFormat[] footer = new MessageFormat[6];

                        // Assign the 6 Strings to the footer array
                        footer[0] = new MessageFormat("Authorizer Signature:______________  Date:___ /___ /_____ ");
                        footer[1] = new MessageFormat("");
                        footer[2] = new MessageFormat("");
                        footer[3] = new MessageFormat("Notarizer Signature:______________  Date:___ /___ /_____ ");
                        footer[4] = new MessageFormat("");
                        footer[5] = new MessageFormat("- {0} -");
*/              
                        
                        jTableStudentRecord.print();
                        //job.print();
                } catch (PrinterException e) {
                        System.err.format("Cannot print %s%n", e.getMessage());

                        JOptionPane.showMessageDialog(this,
                                "Check that your printer is working correctly", "PRINT ERROR", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel dtablemodel = (DefaultTableModel) jTableStudentRecord.getModel();
        if (jTableStudentRecord.getSelectedRow() == -1) {
            if (jTableStudentRecord.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data to delete", "Student Data Management System", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to delete", "Student Data Management System", JOptionPane.OK_OPTION);
            }
        } else {
            dtablemodel.removeRow(jTableStudentRecord.getSelectedRow());
            //int row = jTableStudentRecord.getSelectedRow();
            //String deleteLineRecord = jTableStudentRecord.getModel().getValueAt(row, 0).toString();
            //String sql = "DELETE FROM \"StudentData\" WHERE \"Student_ID\" = " + row;

            try {
                //pst = connection.prepareStatement(sql);
                //pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    // add new student data to table
    public void updateTable() {
        
        connection = StudentMS.ConnectDb();
        if (connection != null) {
        
            String sql = "SELECT \"Student_ID\", \"CourseCode\", \"Math\", \"English\", "
                    + "\"Biology\", \"InfoTech\", \"Chemistry\", \"Physic\", \"AddMath\", \"Business\", \"TotalScore\", "
                    + "\"Average\", \"Ranking\" FROM \"StudentData\"";

            try {
                pst = connection.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object[13];

                while(rs.next()) {
                    columnData [0] =rs.getString("Student_ID");
                    columnData [1] =rs.getString("CourseCode");
                    columnData [2] =rs.getInt("Math");
                    columnData [3] =rs.getInt("English");
                    columnData [4] =rs.getInt("Biology");
                    columnData [5] =rs.getInt("InfoTech");
                    columnData [6] =rs.getInt("Chemistry");
                    columnData [7] =rs.getInt("Physic");
                    columnData [8] =rs.getInt("AddMath");
                    columnData [9] =rs.getInt("Business");
                    columnData [10] =rs.getInt("TotalScore");
                    columnData [11] =rs.getInt("Average");
                    columnData [12] =rs.getString("Ranking"); 
                    // DefaultTableModel instance is created as dtablemodel
                    dtablemodel.addRow(columnData);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMS().setVisible(true);
            }
        });
    }
    
    public static Connection ConnectDb() {
        try {
            //Class.forName("org.sqlite.JDBC");
            Class.forName("org.postgresql.Driver");
            //embedded database DriverManager.getConnection("jdbc:sqlite:StudentDataMS.db");
            String dbUrl = "jdbc:postgresql://" + "ec2-54-235-208-103.compute-1.amazonaws.com" + "d3mk22kabev5b6?sslmode=require"; //connect to db from local machine
            String user = "yleofehjfeypnh";
            String pw = "925264deb4c3a72f8202e6ea6cc9e6041cd27b4bba08427377d171f7026232cf";
            //Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/StudentDataMS", "postgres", "md5");
            Connection connection = DriverManager.getConnection(dbUrl, user, pw);
            return connection;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCourseCode;
    private javax.swing.JLabel jLabelAddMath;
    private javax.swing.JLabel jLabelAverage;
    private javax.swing.JLabel jLabelBiology;
    private javax.swing.JLabel jLabelBusiness;
    private javax.swing.JLabel jLabelChemistry;
    private javax.swing.JLabel jLabelCourseCode;
    private javax.swing.JLabel jLabelEnglish;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelInfoTech;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMath;
    private javax.swing.JLabel jLabelPhysic;
    private javax.swing.JLabel jLabelRanking;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JLabel jLabelTotalScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableStudentRecord;
    private javax.swing.JTextArea jTextAreaTranscript;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnResult;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JTextField jtxtAddMath;
    private javax.swing.JTextField jtxtAverage;
    private javax.swing.JTextField jtxtBiology;
    private javax.swing.JTextField jtxtBusiness;
    private javax.swing.JTextField jtxtChemistry;
    private javax.swing.JTextField jtxtEnglish;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtInfoTech;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtMath;
    private javax.swing.JTextField jtxtPhysic;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtTotalScore;
    // End of variables declaration//GEN-END:variables
}
